### PR TITLE
Makes JSHint and JSCS tasks pass

### PR DESCRIPTION
**Pull request by wyze**
This could also contain other stylistic consistency changes I've noticed while working on the CLI project.

### CODE REVIEW

**Comment by wyze** [comment]
@rwaldron @johnnyman727 .. Can status checks be enabled in this repo? I can do a separate PR for Travis and AppVeyor configs.

**Comment by rwaldron** [comment]
ready for rebase

**Comment by rwaldron** [comment]
I just switched on appveyor

**Comment by johnnyman727** [comment]
Travis CI also switched on.

**Comment by wyze** [comment]
Removed WIP tag as this is ready for review/merge!

**Comment by rwaldron** [comment]
WOW. This is really amazing work.

You confirmed that all functionality is still intact? Specifically, did you run existing code that uses the ambient module, to confirm that nothing was inadvertently broken? (It happens)

**Comment by wyze** [comment]
I will double check it on hardware tonight. Tessel 1 and Tessel 2 to confirm. Is there more extensive hardware test than what is in `examples/` and `debug/` that I could run as well?

**Comment by rwaldron** [comment]
I would be satisfied by confirmation of those items, but @johnnyman727 should sign off on that specifically.

**Comment by johnnyman727** [comment]
I think you should also run the four hardware tests in the test folder.

If I were a betting man, I would guess that something about these changes will fail on T1. If that's the case, I vote for bumping the minor/major version and leaving T1 compat behind.

**Comment by wyze** [comment]
There are no hardware tests for t2. But the hardware tests do pass for t1. Also, both examples run on both Tessels and behave as they are supposed to.

```
~/Projects/tessel/ambient-attx4 jshint-jscs-fixes
❯ nr tap-tessel-1

> ambient-attx4@0.2.8 tap-tessel-1 /Users/neil/Projects/tessel/ambient-attx4
> tinytap -e 't1 run {} ${AMBIENT_PORT}' test/*.js

1..8
ok 1 - test/apiTest.js
ok 2 - test exited with code 0
ok 3 - test/flashVerify.js
ok 4 - test exited with code 0
ok 5 - test/listeners.js
ok 6 - test exited with code 0
ok 7 - test/simple.js
ok 8 - test exited with code 0
```

**Comment by wyze** [comment]
The Travis tests are being flakey right now. @johnnyman727 can you try to rerun them please?

**Comment by rwaldron** [comment]
> There are no hardware tests for t2

Sorry if this is a dumb question: can you run the existing T1 stuff on the T2?

**Comment by wyze** [comment]
> Sorry if this is a dumb question: can you run the existing T1 stuff on the T2?

Honestly I didn't even try, but they might be compatible. The [package.json#L8-L9](https://github.com/tessel/ambient-attx4/blob/master/package.json#L8-L9) gives the impression that they should be different. I can replicate the command for `tinytap` and make it execute the `t2` command instead and report back.

**Comment by rwaldron** [comment]
## Smoke Tests

With a Tessel 2 and the Ambient module attached to Port A: 


1. Pulled the branch to my local

  ```sh
  git checkout -b wyze-jshint-jscs-fixes master
  git pull https://github.com/wyze/ambient-attx4.git jshint-jscs-fixes
  ```

2. Confirm test suite passes

  ```sh
  rwaldron at nova in ~/clonez/ambient-attx4 on wyze-jshint-jscs-fixes
  $ grunt
  Running "jshint:all" (jshint) task
  >> 2 files lint free.

  Running "jshint:tests" (jshint) task
  >> 7 files lint free.

  Running "jscs:all" (jscs) task
  >> 9 files without code style errors.

  Running "jsbeautifier:all" (jsbeautifier) task
  Beautified 9 files, changed 0 files...OK

  Running "nodeunit:tests" (nodeunit) task
  Testing index.js.OK
  >> 1 assertions passed (53ms)

  Done, without errors.
  ```

3. examples/ambient.js
  1. Clap twice
  2. Shine flashlight (phone flash will do) on sensor
  ```sh
  rwaldron at nova in ~/clonez/ambient-attx4 on wyze-jshint-jscs-fixes
  $ t2 run examples/ambient.js
  INFO Looking for your Tessel...
  INFO Connected to bishop.
  INFO Building project.
  INFO Writing project to RAM on bishop (42.496 kB)...
  INFO Deployed.
  INFO Running examples/ambient.js...
  Old module firmware detected. Updating...
  Uploading new firmware...
  Update finished!
  
  # NOTE: I've intentionally omitted the first ~50 log lines for brevity

  Light level: 0.01464844   Sound Level: 0.10742188
  Light level: 0.01367188   Sound Level: 0.14648438
  Light level: 0.01464844   Sound Level: 0.14550781
  Light level: 0.01171875   Sound Level: 0.13867188
  Light level: 0.01269531   Sound Level: 0.13183594
  Light level: 0.01269531   Sound Level: 0.07421875
  Light level: 0.01171875   Sound Level: 0.02539063
  Light level: 0.01464844   Sound Level: 0.01074219
  Light level: 0.01562500   Sound Level: 0.01171875
  Light level: 0.01757813   Sound Level: 0.01171875
  Light level: 0.01757813   Sound Level: 0.00878906
  Light level: 0.01562500   Sound Level: 0.01074219
  Light level: 0.01562500   Sound Level: 0.01367188
  Light level: 0.01562500   Sound Level: 0.01171875
  Light level: 0.01562500   Sound Level: 0.01171875
  Light level: 0.01464844   Sound Level: 0.00878906
  Light level: 0.01562500   Sound Level: 0.00878906
  Light level: 0.01562500   Sound Level: 0.01464844
  Light level: 0.08398438   Sound Level: 0.00878906
  Light level: 0.21093750   Sound Level: 0.00781250
  Light level: 0.24511719   Sound Level: 0.00878906
  Light level: 0.26367188   Sound Level: 0.01367188
  Light level: 0.22460938   Sound Level: 0.00878906
  Light level: 0.09765625   Sound Level: 0.01367188
  Light level: 0.03515625   Sound Level: 0.01367188
  Light level: 0.17968750   Sound Level: 0.00878906
  Light level: 0.24316406   Sound Level: 0.01367188
  Light level: 0.17871094   Sound Level: 0.00683594
  Light level: 0.15429688   Sound Level: 0.01367188
  Light level: 0.05761719   Sound Level: 0.01171875
  ``` 

4. examples/ambient-triggers.js
  1. Clap once
  2. Shine flashlight (phone flash will do) on sensor
  ```sh
  $ t2 run examples/ambient-triggers.js
  INFO Looking for your Tessel...
  INFO Connected to bishop.
  INFO Building project.
  INFO Writing project to RAM on bishop (43.008 kB)...
  INFO Deployed.
  INFO Running examples/ambient-triggers.js...
  Waiting for a bright light or a sound...
  Something happened with sound:  0.1669921875
  Our light trigger was hit: 0.5009765625
  ```  

5. test/apiTest.js

  ```sh
  $ t2 run test/apiTest.js
  INFO Looking for your Tessel...
  INFO Connected to bishop.
  INFO Building project.
  INFO Writing project to RAM on bishop (67.584 kB)...
  INFO Deployed.
  INFO Running test/apiTest.js...
  1..101
  # Connecting to ambient module, checking events
  ok 1 ok
  ok 2 equal
  ok 3 ok
  ok 4 ok
  ok 5 ok
  ok 6 equal
  ok 7 ok
  ok 8 equal
  ok 9 ok
  ok 10 equal
  ok 11 ok
  ok 12 equal
  ok 13 ok
  ok 14 equal
  ok 15 ok
  ok 16 equal
  ok 17 ok
  ok 18 equal
  ok 19 ok
  ok 20 equal
  ok 21 ok
  ok 22 equal
  ok 23 ok
  ok 24 equal
  ok 25 ok
  ok 26 ok
  ok 27 ok
  ok 28 equal
  ok 29 ok
  ok 30 equal
  ok 31 ok
  ok 32 equal
  ok 33 ok
  ok 34 equal
  ok 35 ok
  ok 36 equal
  ok 37 ok
  ok 38 equal
  ok 39 ok
  ok 40 equal
  ok 41 ok
  ok 42 equal
  ok 43 ok
  ok 44 equal
  ok 45 ok
  ok 46 equal
  ok 47 ok
  # light trigger tests
  ok 48 ok
  ok 49 equal
  ok 50 ok
  ok 51 ok
  # sound trigger tests
  ok 52 ok
  ok 53 equal
  ok 54 ok
  ok 55 ok
  # getLightBuffer
  ok 56 ok
  ok 57 equal
  ok 58 ok
  ok 59 equal
  ok 60 ok
  ok 61 equal
  ok 62 ok
  ok 63 equal
  ok 64 ok
  ok 65 equal
  ok 66 ok
  ok 67 equal
  ok 68 ok
  ok 69 equal
  ok 70 ok
  ok 71 equal
  ok 72 ok
  ok 73 equal
  ok 74 ok
  ok 75 equal
  ok 76 ok
  # getLightLevel
  ok 77 equal
  ok 78 ok
  # getSoundBuffer
  ok 79 ok
  ok 80 equal
  ok 81 ok
  ok 82 equal
  ok 83 ok
  ok 84 equal
  ok 85 ok
  ok 86 equal
  ok 87 ok
  ok 88 equal
  ok 89 ok
  ok 90 equal
  ok 91 ok
  ok 92 equal
  ok 93 ok
  ok 94 equal
  ok 95 ok
  ok 96 equal
  ok 97 ok
  ok 98 equal
  ok 99 ok
  # getSoundLevel
  ok 100 equal
  ok 101 ok
  # pass 101 101
  # fail 0 101
  ```

6. test/flashVerify.js
  - Skipped because this didn't pass on `master` 
  

7. test/listeners.js


  ```sh
  $ t2 run test/listeners.js
  INFO Looking for your Tessel...
  INFO Connected to bishop.
  INFO Building project.
  INFO Writing project to RAM on bishop (47.616 kB)...
  INFO Deployed.
  INFO Running test/listeners.js...
  1..1
  # Using multiple kinds of listeners
  ok 1 equal
  # pass 1 1
  # fail 0 1
  ```

8. test/simple.js

  ```sh
  $ t2 run test/simple.js
  INFO Looking for your Tessel...
  INFO Connected to bishop.
  INFO Building project.
  INFO Writing project to RAM on bishop (42.496 kB)...
  INFO Deployed.
  INFO Running test/simple.js...

  # connecting on port A
  1..2
  # light [ 0.015625,
    0.015625,
    0.0185546875,
    0.015625,
    0.015625,
    0.015625,
    0.0185546875,
    0.0185546875,
    0.0185546875,
    0.015625 ]
  ok
  # sound [ 0.01171875,
    0.01171875,
    0.0107421875,
    0.013671875,
    0.0146484375,
    0.0087890625,
    0.0146484375,
    0.0107421875,
    0.013671875,
    0.01171875 ]
  ok
  ```


@wyze 

**Great work!**

This can be merged to master when you're ready.

**Comment by wyze** [comment]
Thanks @rwaldron. 👍

**Comment by rwaldron** [comment]
@wyze my pleasure :)

**Pull request merged**
