### PR TITLE
run callback if present, else emit an error

### PR DESCRIPTION
**Pull request by seiyria**
more discussion can be found in #56

### CODE REVIEW

**Comment by johnnyman727** [comment]
:+1: Looks good! Could you sign [our CLA if you haven't already](dojofoundation.org/about/claForm) and ping me when that's done?

**Comment by seiyria** [comment]
Done!

**Comment by johnnyman727** [comment]
Awesome, thanks! I'll try to make a few other ambient related fixes and get a new version published by the end of the week.

**Comment by seiyria** [comment]
Great to hear. Hopefully this will also cover the constant "updating firmware" message I see with the ambient module.

**Pull request merged**
