### PR TITLE
Ensures firmware file will be deployed to T2 and updates deps

### PR DESCRIPTION
**Pull request by johnnyman727**
Should be merged after https://github.com/tessel/attiny-common/pull/4 is deployed to npm.

### CODE REVIEW

**Comment by rwaldron** [comment]
Is there any easy way to confirm that the firmware has been pushed out to the attiny?

**Comment by johnnyman727** [comment]
@rwaldron I think the best way would just be to use `fs.exists`. Are you hinting at some missing units tests? :)

**Comment by rwaldron** [comment]
No no, I meant on the actual μC itself... I have an attiny programmer and I'm wondering if I can use that to just confirm for myself?

**Comment by johnnyman727** [comment]
Oh gotcha. You can modify the code to just call [the function to check the code CRC](https://github.com/tessel/attiny-common/blob/master/lib/index.js#L227) upon initialization and confirm that it matches the [expected CRC](https://github.com/tessel/ambient-attx4/blob/master/index.js#L35).

**Comment by johnnyman727** [comment]
Okay I finally got around to testing this on T1. It looks like firmware updates have been non-functional on T1 for some indefinite about of time. I reported the issue here: https://github.com/tessel/attiny-common/issues/6.

I also found out that updating doesn't always work on T2 (potentially due to the same root cause(s)). Those issues have been reported as https://github.com/tessel/ambient-attx4/issues/50 and https://github.com/tessel/attiny-common/issues/5. 

Seeing as these issues have existed prior to this PR on T1 and it only *adds* functionality for T2, there is no reason not to merge this PR now and put out an `npm` release that allows the module to be used on T2.

**Comment by johnnyman727** [comment]
I haven't heard any dissenting opinions so I will move forward with releasing new versions of `avr-isp`, `attiny-common` and this ambient module (with this PR).

**Comment by rwaldron** [comment]
@johnnyman727 I've been trying to get my ambient module updated for hours and it just won't work, any ideas? When I look at the files that get deployed, everything is there, but regardless: 

```
$ t2 run index.js
INFO Looking for your Tessel...
INFO Connected to bishop.
INFO Building project.
INFO Writing project to RAM on bishop (42.496 kB)...
INFO Deployed.
INFO Running index.js...
Old module firmware detected. Updating...
[Error: Unable to update firmware: Programming confirmation not received.]
```

**Comment by rwaldron** [comment]
I will open a new issue

**Pull request merged**
